export default {
    clickStart: 'clickstart',
    Settlement: 'settlement',
    ReStart: 'reStart',
    ShowWarn: 'ShowWarn',
    HideWarn: 'HideWarn',
    addHP:'addHP',
    OverGame:'OverGame',
    EndMove:'EndMove',
    TryMove:'tryMove',
    ShowScore:'showScore',
    Bomb:'bomb',
    startClock:'startClock',
    Resurrection: 'resurrection',
    SetSXFlag: 'setSanXiaoFlag',

    //音效
    micStartBtn: 'msgStartBtn',
    micbutton: 'msgbutton',
    micBomb: 'clickbomb',
    micMinHP: 'clickBG',
    micClickShape: 'clickShape',
    micClickStart: 'clickStart',
    micclickCombo: 'clickCombo',
}
